### ISSUE TITLE
新建uniapp组件，文件内容少了export defult 的结束  }

### ISSUE THREAD

**Issue by inprivacy** [TuiMao233/create-uniapp-view#14]
新建uniapp组件，文件内容少了export defult 的结束  }

**Comment by inprivacy** [comment]
![image](https://user-images.githubusercontent.com/45675543/185349987-da862835-3c2d-46c7-a3df-d6c2cb63919f.png)

**Comment by YellowOrangeHuang** [comment]
这个我也遇到过
