### ISSUE TITLE
生成的Vue文件模板，data 不应该为箭头函数

### ISSUE THREAD

**Issue by RJM1996** [TuiMao233/create-uniapp-view#9]
<img width="379" alt="image" src="https://user-images.githubusercontent.com/33800707/175455922-966d8958-7ab8-4eb2-897a-5bfa0c0d1fe0.png">

现在生成的Vue模板，data 属性是一个箭头函数，这样会导致使用 this 无法访问到当前实例
因为 Vue 源码中使用 call 更改 data 函数的 this 绑定，但是箭头函数本身没有 this，无法更改

<img width="564" alt="image" src="https://user-images.githubusercontent.com/33800707/175456104-636d1021-46b0-4095-8f95-49b6c3bc30de.png">

**Comment by TuiMao233** [comment]
在 https://github.com/TuiMao233/create-uniapp-view/commit/14e7dba79f3d178525856a6c6f103b6627bad65e 中得到修复
